-- Update emergency_response_guide for ALL products
-- Generated from CSV data

UPDATE products SET emergency_response_guide = '128' WHERE name = 'Berry Clean';
UPDATE products SET emergency_response_guide = 'Not applicable.<br>

In containers of 119 gallons or less this product is not regulated by DOT. Shipments in containers of more than 119 gallons, this product is regulated by DOT and must ship as flammable liquid.' WHERE name = 'All Shield EX';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'Clean Lift 20/20';
UPDATE products SET emergency_response_guide = '128' WHERE name = 'Crystal Shine SC Matte';
UPDATE products SET emergency_response_guide = '128' WHERE name = 'Crystal Shine HS SC Matte';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'Cure & Seal WB 30';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'Cure & Seal WB';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'Cure Shield WB';
UPDATE products SET emergency_response_guide = '128' WHERE name = 'Deco Shine Matte';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'Final Finish';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'IntraFilm';
UPDATE products SET emergency_response_guide = '157' WHERE name = 'Muriatic Acid';
UPDATE products SET emergency_response_guide = 'Corrosive' WHERE name = 'MVM Prime 5000 (Part B)';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'Pave Cure Rez w Dye';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'Pave Cure WW 300';
UPDATE products SET emergency_response_guide = 'None' WHERE name = 'Rapid Flex 90';
UPDATE products SET emergency_response_guide = 'None' WHERE name = 'Rapid Flex 90';
UPDATE products SET emergency_response_guide = 'None' WHERE name = 'Rapid Flex 90';
UPDATE products SET emergency_response_guide = 'None' WHERE name = 'Rapid Flex 90';
UPDATE products SET emergency_response_guide = 'None' WHERE name = 'Rapid Flex 90';
UPDATE products SET emergency_response_guide = 'None' WHERE name = 'Rapid Flex 90';
UPDATE products SET emergency_response_guide = 'None' WHERE name = 'Rapid Flex 90';
UPDATE products SET emergency_response_guide = 'None' WHERE name = 'Rapid Flex 90';
UPDATE products SET emergency_response_guide = 'Not applicable.<br>

In containers of 119 gallons or less this product is not regulated by DOT. Shipments in containers of more than 119 gallons, this product is regulated by DOT and must ship as flammable liquid.' WHERE name = 'Poly Fix (Part A)';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'RepCon 928';
UPDATE products SET emergency_response_guide = 'Not applicable.<br>

In containers of 119 gallons or less this product is not regulated by DOT. Shipments in containers of more than 119 gallons, this product is regulated by DOT and must ship as flammable liquid.' WHERE name = 'Poly Fix (Part B)';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'Spec CJ Guard';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'SpecPlug MKS';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecPoxy 3000 (Part A)';
UPDATE products SET emergency_response_guide = 'US DOT regulated' WHERE name = 'SpecPoxy Coating Gray (Part B)';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecPrep SB (Part C)';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecRez (Concentrate)';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecSilane 20 WB';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecSilane 40 WB';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecStrip WB Concentrate';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'Super SpecPlug';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'TriAct';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'Versa Etch Micro Etch #3';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'Versa Etch Coarse #125';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'Versa Etch Extender';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'All Shield WB';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'Bio Strip WB';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'Bio Strip WB Concentrate';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'C-Set';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'Concrete Cure w/Dye';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'Concrete Glue';
UPDATE products SET emergency_response_guide = '153' WHERE name = 'Crete-Away';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'Crystal Rez w/ Dye';
UPDATE products SET emergency_response_guide = '128' WHERE name = 'Crystal Shine';
UPDATE products SET emergency_response_guide = '128' WHERE name = 'Crystal Shine HS';
UPDATE products SET emergency_response_guide = '128' WHERE name = 'Crystal Shine HS SC';
UPDATE products SET emergency_response_guide = '128' WHERE name = 'Crystal Shine Matte';
UPDATE products SET emergency_response_guide = '128' WHERE name = 'Crystal Shine HS Matte';
UPDATE products SET emergency_response_guide = '128' WHERE name = 'Crystal Shine SC';
UPDATE products SET emergency_response_guide = '128' WHERE name = 'Cure & Seal 25';
UPDATE products SET emergency_response_guide = '128' WHERE name = 'Cure & Seal 25 EX';
UPDATE products SET emergency_response_guide = '128' WHERE name = 'Cure & Seal 25 UV';
UPDATE products SET emergency_response_guide = '128' WHERE name = 'Cure & Seal 30 EX';
UPDATE products SET emergency_response_guide = '128' WHERE name = 'Cure & Seal EX';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'Cure & Seal WB 25';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'Cure Hard';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'Cure Hard Clear';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'Cure Hard Concentrate';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'Cure Hard Plus';
UPDATE products SET emergency_response_guide = '128' WHERE name = 'Cure Shield';
UPDATE products SET emergency_response_guide = '128' WHERE name = 'Cure Shield EX';
UPDATE products SET emergency_response_guide = '128' WHERE name = 'Deco Liquid Release';
UPDATE products SET emergency_response_guide = '128' WHERE name = 'Deco Shine Brown';
UPDATE products SET emergency_response_guide = '128' WHERE name = 'Deco Shine';
UPDATE products SET emergency_response_guide = '128' WHERE name = 'Deco Shine Brown EX';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'E-Cure®';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'Duo Patch';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'E-Cure (No Dye)';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'E-Cure® Concentrate';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'EZ Clean & Release';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'EZ Clean & Release Cherry';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'Fencement';
UPDATE products SET emergency_response_guide = 'Corrosive' WHERE name = 'Form Seasoning WB';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'Intracon';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'IntraFilm Concentrate';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'K-Set';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'LithSeal Lite';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'LithSeal SC';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'LithSeal SG';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'MVM Prime 5000 (Part A)';
UPDATE products SET emergency_response_guide = '128' WHERE name = 'Orange Peel<sup>®</sup>';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'OverCrete Coarse';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'OverCrete Fine';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'Pave Cure AMS';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'Pave Cure AMS Caltrans';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'Pave Cure CW';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'Pave Cure CW Caltrans';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'Pave Cure CW with Dye';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'Pave Cure CW with Dye TX Type I';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'Pave Cure Rez Clear';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'Pave Cure Rez Clear Caltrans';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'Pave Cure Rez Clear TX Type I';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'Pave Cure Rez Guard';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'Pave Cure Rez White';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'Pave Cure Rez White Caltrans';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'Pave Cure Rez White Guard';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'Pave Cure Rez White TX Type II';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'Pave Cure WW';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'Pave Cure WW Caltrans';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'Pave Cure WW TX Type II';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'Plaster Bond';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'Plaster Bond';
UPDATE products SET emergency_response_guide = '128' WHERE name = 'PolyCure';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'Por-Rok';
UPDATE products SET emergency_response_guide = 'None' WHERE name = 'Rapid Flex CJ';
UPDATE products SET emergency_response_guide = 'None' WHERE name = 'Rapid Flex CJ';
UPDATE products SET emergency_response_guide = 'None' WHERE name = 'Rapid Flex CJ';
UPDATE products SET emergency_response_guide = 'None' WHERE name = 'Rapid Flex CJ';
UPDATE products SET emergency_response_guide = 'None' WHERE name = 'Rapid Flex CJ';
UPDATE products SET emergency_response_guide = 'None' WHERE name = 'Rapid Flex CJ';
UPDATE products SET emergency_response_guide = 'None' WHERE name = 'Rapid Flex CJ';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'RepCon H';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'RepCon UW Mortar';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'RepCon H-350';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'RepCon V/O';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'RepCon® 928 FS';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'RepCon® V/O';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'RePlug';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'RevCrete™';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SC Concrete Finish';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SC Cure 500';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SC Foundation Coating';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SC Metallic Grout';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SC MT Black Pigment';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SC Multi-Purpose Sealer';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SC Multipurpose Grout';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SC Precision Grout';
UPDATE products SET emergency_response_guide = 'Class B2, D2B (Flammable, Toxic)' WHERE name = 'Sealer Renew';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'Sleek 1000 SLU';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'Sodium Silicate';
UPDATE products SET emergency_response_guide = 'Class B2, D2B (Flammable, Toxic)' WHERE name = 'Solvent 100';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'Sonic Rock';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'Spec-O-Lith';
UPDATE products SET emergency_response_guide = 'Class E, D2B (Corrosive, Toxic)' WHERE name = 'SpecBlast';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecCity White';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecCity White Concentrate';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecCity White STX';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'SpecEtch';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'SpecEtch Clear';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'SpecEtch Deep';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecFilm';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecFilm Clear';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecFilm Concentrate';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'SpecFilm NuWay';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'SpecFilm RTU';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'SpecFilm Yellow';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecLevel PCT';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'SpecLevel PCT-AGG';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecPatch 15';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecPatch 30';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecPatch 30-Light';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecPatch 5';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecPatch Light';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'SpecPlate';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'SpecPlate Topping';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecPlug';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecPoxy 1000 (Part A)';
UPDATE products SET emergency_response_guide = 'Class E, D2B' WHERE name = 'SpecPoxy 1000 (Part B)';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecPoxy 2000 (Part A)';
UPDATE products SET emergency_response_guide = 'Class E, D2B' WHERE name = 'SpecPoxy 2000 (Part B)';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'SpecPoxy 2000 LPL (Part A)';
UPDATE products SET emergency_response_guide = 'US DOT: regulated' WHERE name = 'SpecPoxy 2000 LPL (Part B)';
UPDATE products SET emergency_response_guide = 'Class E, D2B' WHERE name = 'SpecPoxy 3000 FS (Part B)';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecPoxy 500 (Part A)';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecPoxy 3000 FS (Part A)';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'SpecPoxy Binder (Part A)';
UPDATE products SET emergency_response_guide = 'US DOT regulated' WHERE name = 'SpecPoxy Binder (Part B)';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'SpecPoxy Bridge Overlay (Part A)';
UPDATE products SET emergency_response_guide = 'Class E, D2B' WHERE name = 'SpecPoxy Bridge Overlay (Part B)';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecPoxy CJ (Part A)';
UPDATE products SET emergency_response_guide = 'Class E, D2B' WHERE name = 'SpecPoxy CJ (Part B)';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'SpecPoxy CJ Yellow (Part A)';
UPDATE products SET emergency_response_guide = 'US DOT regulated' WHERE name = 'SpecPoxy CJ Yellow (Part B)';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecPoxy Coating Clear (Part A)';
UPDATE products SET emergency_response_guide = 'Class E, D2B' WHERE name = 'SpecPoxy Coating Clear (Part B)';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecPoxy Coating Gray (Part A)';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'SpecPoxy Grout (Part A)';
UPDATE products SET emergency_response_guide = 'US DOT regulated' WHERE name = 'SpecPoxy Grout (Part B)';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecPoxy Grout (Part C)';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'SpecPoxy Grout HS (Part A)';
UPDATE products SET emergency_response_guide = 'US DOT regulated' WHERE name = 'SpecPoxy Grout HS (Part B)';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'SpecPoxy Grout HS (Part C)';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'SpecPoxy Mortar (Part A)';
UPDATE products SET emergency_response_guide = 'US DOT regulated' WHERE name = 'SpecPoxy Mortar (Part B)';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'SpecPoxy Mortar (Part C)';
UPDATE products SET emergency_response_guide = '128' WHERE name = 'SpecPoxy Sealer (Part A)';
UPDATE products SET emergency_response_guide = '128' WHERE name = 'SpecPoxy Sealer (Part B)';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecPrime';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecRez';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecRez W/ Dye';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecShield WB';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecStrip';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'Specstrip Cherry';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'Specstrip Citrus';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecStrip Plus';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecStrip Red';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecStrip Ultra Blue';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecStrip VOC 100';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecStrip WB';
UPDATE products SET emergency_response_guide = '128' WHERE name = 'SpecTilt EX';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecTilt WB';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecWeld';
UPDATE products SET emergency_response_guide = 'Class B2, D2B' WHERE name = 'Stripper Supreme';
UPDATE products SET emergency_response_guide = 'Improves bonding and durability of concrete and masonry.' WHERE name = 'Strong Bond';
UPDATE products SET emergency_response_guide = 'Enhances adhesion and durability of cementitious materials.' WHERE name = 'Strong Bond Concentrate';
UPDATE products SET emergency_response_guide = 'Improves adhesion of stucco and plaster to vertical and horizontal surfaces.' WHERE name = 'Stucco Bond';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'Stucco Bond Blue';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'Stucco Bond White';
UPDATE products SET emergency_response_guide = '128' WHERE name = 'Surface Shine';
UPDATE products SET emergency_response_guide = '128' WHERE name = 'Surface Shine Brown';
UPDATE products SET emergency_response_guide = '128' WHERE name = 'Surface Shine Brown EX';
UPDATE products SET emergency_response_guide = '128' WHERE name = 'Surface Shine EX';
UPDATE products SET emergency_response_guide = '128' WHERE name = 'Surface Shine Gray EX';
UPDATE products SET emergency_response_guide = 'Flammable Liquid' WHERE name = 'Surface Shine HS EX';
UPDATE products SET emergency_response_guide = '128' WHERE name = 'Surface Shine Slate';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'Surface Shine WB';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'Total Patch';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'UW Admixture';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'UW Grout';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'V Form Release #1';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'V Form Release #1 Citrus';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'V Release #100';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'V Release Concentrate';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'V Release Winter Grade';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'Versa Etch Fine #25';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'Versa Etch Light Etch #15';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'Versa Etch Medium #75';
UPDATE products SET emergency_response_guide = '128' WHERE name = 'Xylene';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'Versa Etch Sandblast #5';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'Versa Etch Zero #1';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'Aqua Shine';
UPDATE products SET emergency_response_guide = 'Not applicable' WHERE name = 'SpecStrip Citrus Winter Grade';
UPDATE products SET emergency_response_guide = 'Not regulated' WHERE name = 'IntraHard';
